app:
  version: '1.0.0'
  hostname: '<HOSTNAME-HERE>' # omsdev
  supported-databases: ['altibase', 'timesten', 'voltdb'] # you can delete unused items
slack:
  is-active: true
  send-help-msg: true
  token: '<SLACK-TOKEN-HERE>' # xoxb-15....
  webhook-url: '<SLACK-WEBHOOK-URL-HERE>' # https://hooks.slack.com/services/T32...
  bot-name: '<SLACK-BOT-NAME-HERE>' # bob
  channel-name: '<SLACK-CHANNEL-HERE>' # general
  commands: {
    # command: worker
    altibase-status: 'altibase',
    timesten-status: 'timesten',
    voltdb-status: 'voltdb',
    memusage: 'resource',
    cpuusage: 'resource'
  }
  seconds-sleep-after-slack-poll: 2
altibase:
  is-active: true
  bin-dir: '<ALTIBASE-BIN-DIR-HERE>' # /home/altibase/ALTIBASE_COMMUNITY_EDITION_SERVER/bin/
  bin-isql: 'isql'
  bin-status: ''
  conn-str: '-s <SERVER-NAME-HERE> -u <USER-NAME-HERE> -p <PASSWORD-HERE>' # -s 127.0.0.1 -u hodor -p hodor
  seconds-sleep-after-status-check: 5
  seconds-error-msg-flood-protection: 300
  parser: {
    isql: {
      'ClusterState': ['', ''],
      'StartTime': ['', ''],
      'Uptime': ['', '']
    }
  }
timesten:
  is-active: false
  bin-dir: '<TIMESTEN-BIN-DIR-HERE>' # ~/TimesTen/tt1122/bin/
  bin-isql: 'isql'
  bin-status: 'ttstatus'
  conn-str: '-connStr <TIMESTEN-CONNSTR-HERE>' # "DSN=TT_1122;"
  seconds-sleep-after-status-check: 5
  seconds-error-msg-flood-protection: 300
  parser: {
    isql: {
      'ClusterState': ['', ''],
      'StartTime': ['', ''],
      'Uptime': ['', '']
    }
  }
voltdb:
  is-active: false
  bin-dir: '<VOLTDB-BIN-DIR-HERE>' # ~/voltdb/voltdb-ent-7.0/bin/
  bin-isql: 'sqlcmd'
  bin-status: ''
  conn-str: '<VOLTDB-CONNSTR-HERE>' # --servers=odin --user=thor --password=loki.sucks
  seconds-sleep-after-status-check: 5
  seconds-error-msg-flood-protection: 300
  parser: {
    isql: {
      'ClusterState': ['Cluster State', '.*CLUSTERSTATE\s+(\w+)\s{2,}'],
      'StartTime': ['Start Time', '.*STARTTIME\s+(.*)\s{2,}'],
      'Uptime': ['Uptime', '.*UPTIME\s+(.*)\s{2,}']
    }
  }
resource:
  notify-memory-usage: true
  notify-cpu-usage: true
  notify-disk-usage: false
  cpu-usage-percent-threshold: 60
  cpu-circular-buffer-maxlen: 10
  cpu-notification-threshold-count: 7
  seconds-sleep-after-run : 5
  seconds-error-msg-flood-protection: 300