app:
  version: '0.0.1'
  hostname: 'omsdev'
  supported-databases: ['altibase', 'timesten', 'voltdb']
slack:
  is-active: true
  send-help-msg: true
  token: '<SLACK-TOKEN-HERE>' # xoxb-15....
  webhook-url: '<SLACK-WEBHOOK-URL-HERE>' # https://hooks.slack.com/services/T32...
  bot-name: '<SLACK-BOT-NAME-HERE>' # bob
  channel-name: '<SLACK-CHANNEL-HERE>' # general
  commands: {
    # command: worker
    altibase: 'altibase',
    timesten-status: 'timesten',
    voltdb-status: 'voltdb'
  }
  seconds-sleep-after-slack-poll: 2
altibase:
  is-active: true
  bin-dir: ''
  bin-isql: ''
  bin-status: ''
  conn-str: ''
  pipe_status_check: ['{bin_dir}{bin_status} {conn_str}']
  pipe_status_check: ['', '']
  seconds-sleep-after-status-check: 5
  seconds-error-msg-flood-protection: 300
  parser: {
    isql: {
      'ClusterState': ['', ''],
      'StartTime': ['', ''],
      'Uptime': ['', '']
    }
  }
timesten:
  is-active: true
  bin-dir: '~/timesten/TimesTen/tt1122/bin/'
  bin-isql: 'isql'
  bin-status: 'ttstatus'
  conn-str: '-connStr "DSN=TT_1122;"'
  pipe_status_check: ['{bin_dir}{bin_status} {conn_str}']
  seconds-sleep-after-status-check: 5
  seconds-error-msg-flood-protection: 300
  parser: {
    isql: {
      'ClusterState': ['', ''],
      'StartTime': ['', ''],
      'Uptime': ['', '']
    }
  }
voltdb:
  is-active: true
  bin-dir: '~/voltdb/voltdb-ent-7.0/bin/'
  bin-isql: 'sqlcmd'
  bin-status: ''
  conn-str: ''
  pipe_status_check: ['echo "exec @SystemInformation OVERVIEW;"', '{bin_dir}{bin_isql}']
  seconds-sleep-after-status-check: 5
  seconds-error-msg-flood-protection: 300
  parser: {
    isql: {
      'ClusterState': ['Cluster State', '.*CLUSTERSTATE\s+(\w+)\s{2,}'],
      'StartTime': ['Start Time', '.*STARTTIME\s+(.*)\s{2,}'],
      'Uptime': ['Uptime', '.*UPTIME\s+(.*)\s{2,}']
    }
  }
